### ISSUE TITLE
Self-hosted - no indication that a connection to s3 bucket

### ISSUE THREAD

**Issue by timatlee** [anyproto/any-sync-filenode#143]
### Have you read a contributing guide?

- [x] I have read CONTRIBUTING.md
- [x] I have searched the existing issues and didn't find any that were similar
- [x] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Working with the self-hosted docker solution provided by anyproto. Configured filenode as:

```yaml
network:
// snip
metric:
  addr: 0.0.0.0:8000
log:
  defaultLevel: ''
  namedLevels: {}
  production: true
networkStorePath: "/networkStore"
account:
  peerId: 
  peerKey: 
  signingKey: 
s3Store:
  bucket: anytype
  indexBucket: anytype
  maxThreads: 4
  profile: default
  region: garage
  endpoint: http://192.168.5.87:3900
  forcePathStyle: true
redis:
  isCluster: false
  url: redis://localhost:6379?dial_timeout=3&read_timeout=6s
drpc:
  stream:
    timeoutMilliseconds: 1000
    maxMsgSizeMb: 256
yamux:
  listenAddrs:
    - :1433
  writeTimeoutSec: 10
  dialTimeoutSec: 10
quic:
  listenAddrs:
    - :443
  writeTimeoutSec: 10
  dialTimeoutSec: 10
defaultLimit: 1099511627776
```

I have /root/.aws/credentials configured.  I can connect to the bucket using the aws cli tool with success (`aws --endpoint-url=http://192.168.5.87:3900 --region garage s3 ls`

On startup and run of the filenode, I dont see any indication that there's any files being sent to s3. I think I should be seenig debug messages - `s3store.go` has debug messages in a few of the function calls (Add, Get, Delete, etc.)

The client is showing:

![Image](https://github.com/user-attachments/assets/72348654-aa90-46cb-ae09-16e414fee058)

Content seems to be syncing just fine, but files do not.

If I use an invalid `endpoint` in the configuration, the filenode launches and runs without warning or error.

The defined s3 bucket does not have any data.

Monitoring the logs for the s3 object store, I do not see any connection attempts to the bucket.

### Expected Behavior

Provided s3 configuration to be used. Debug logs indicating that resources are being added or retrieved.

### Steps To Reproduce

git clone
make deps 
make build
bin/any-type-filenode -c etc/config.yml

### Environment

```markdown
- OS: Debian 12 
- Version: v0.8.5, or git main branch
```
